### PR TITLE
1.2.0-beta.1 and show UFDs when call is active

### PR DESCRIPTION
**Pull request by onlysumon**
## Purpose

* Updated communication-calling to 1.1.0-beta.1 version
* Show UFDs when call is in progress

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone https://github.com/onlysumon/communication-services-web-calling-tutorial.git
cd communication-services-web-calling-tutorial
git checkout sharif/ufds
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* `speakingWhileMicrophoneIsMuted` call diagnostic event when call is muted.

### CODE REVIEW

**Review by akania — APPROVED** [review]

**Review by cwhil2492 — APPROVED** [review]

**Comment by onlysumon** [comment]
#sign-off

**Review by ddsmatt — COMMENTED** [review]
review Project/src/MakeCall/MakeCall.js

**Review by ddsmatt — COMMENTED** [review]
onlysumon:sharif/ufds

**Review by ddsmatt — COMMENTED** [review]
gh pr checkout 35

**Pull request merged**
